"""empty message

Revision ID: 585976854a30
Revises: 3b21eb94b9ca
Create Date: 2022-07-16 13:33:00.477573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585976854a30'
down_revision = '3b21eb94b9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
